In [16]:
from sklearn.linear_model import Ridge, Lasso;
from sklearn.metrics import mean_squared_error;
from sklearn.metrics import r2_score;
from sklearn.preprocessing import PolynomialFeatures;
from sklearn.svm import SVR;
from sklearn.svm import SVC;
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor;
from sklearn.ensemble import RandomForestClassifier;
from sklearn.ensemble import RandomForestRegressor;
from sklearn.neighbors import KNeighborsClassifier;
from sklearn.neighbors import KNeighborsRegressor;
from sklearn.naive_bayes import GaussianNB;
import pickle;
import pandas as pd
import numpy as np;
import matplotlib.pyplot as plt;
import seaborn as sns;
from sklearn.impute import SimpleImputer;
from sklearn.compose import ColumnTransformer;
from sklearn.pipeline import Pipeline;
from sklearn.preprocessing import LabelEncoder;
from sklearn.preprocessing import StandardScaler;
from sklearn.preprocessing import MinMaxScaler;
from sklearn.model_selection import train_test_split;
from sklearn.linear_model import LinearRegression ;

In [17]:
df=pd.read_csv("train ratings.csv")

In [18]:
df

,Offered_By,Category,Rating,Reviews,Size,Price,Content_Rating,Last_Updated_On,Release_Version,OS_Version_Required,Downloads
0,ps_id-24654,Finance,4.18,1481,Varies with device,Free,Everyone,May 05 2020,Varies with device,Varies with device,"100,000+"
1,ps_id-35329,Music And Audio,4.81,302,10M,Free,Everyone,Mar 26 2020,3.9.18,4.1 and up,"5,000+"
2,ps_id-11044,Game Casual,4.27,374,27M,Free,Everyone,May 01 2020,1.10.1,4.1 and up,"10,000+"
3,ps_id-36068,Business,4.03,122058,Varies with device,Free,Teen,May 02 2020,Varies with device,Varies with device,"10,000,000+"
4,ps_id-35831,Medical,4.60,358,Varies with device,297.5742,Everyone,Nov 29 2018,Varies with device,Varies with device,"5,000+"
...,...,...,...,...,...,...,...,...,...,...,...
16511,ps_id-5583,Health And Fitness,4.30,13724,Varies with device,Free,Everyone,Sep 21 2018,Varies with device,Varies with device,"1,000,000+"
16512,ps_id-15485,Beauty,4.73,70,7.9M,Free,Everyone,May 07 2020,0.2.5,4.1 and up,"10,000+"
16513,ps_id-36065,Health And Fitness,4.60,5420,21M,Free,Everyone,Jul 10 2019,2.48.3,4.1 and up,"500,000+"
16514,ps_id-12625,Productivity,4.60,1488289,Varies with device,Free,Everyone,Sep 07 2019,Varies with device,Varies with device,"100,000,000+"
16515,ps_id-4549,Game Role Playing,4.45,21201,16M,745.0542,Teen,Sep 20 2019,2.5.17.0,3.0 and up,"100,000+"

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16516 entries, 0 to 16515
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Offered_By           16516 non-null  object
 1   Category             16516 non-null  object
 2   Rating               16516 non-null  float64
 3   Reviews              16516 non-null  int64
 4   Size                 16516 non-null  object
 5   Price                16516 non-null  object
 6   Content_Rating       16516 non-null  object
 7   Last_Updated_On      16516 non-null  object
 8   Release_Version      16516 non-null  object
 9   OS_Version_Required  16516 non-null  object
 10  Downloads            16516 non-null  object
dtypes: float64(1), int64(1), object(9)
memory usage: 1.4+ MB

In [20]:
df.shape

(16516, 11)

In [21]:
df.corr()

           Rating   Reviews
Rating   1.000000  0.030852
Reviews  0.030852  1.000000

In [22]:
df.isnull().sum()

Offered_By             0
Category               0
Rating                 0
Reviews                0
Size                   0
Price                  0
Content_Rating         0
Last_Updated_On        0
Release_Version        0
OS_Version_Required    0
Downloads              0
dtype: int64

In [23]:
df[df['Rating'] == 19]

Empty DataFrame
Columns: [Offered_By, Category, Rating, Reviews, Size, Price, Content_Rating, Last_Updated_On, Release_Version, OS_Version_Required, Downloads]
Index: []

In [24]:
df.iloc[10472,1:] = df.iloc[10472,1:].shift(1)
df[10471:10473]

,Offered_By,Category,Rating,Reviews,Size,Price,Content_Rating,Last_Updated_On,Release_Version,OS_Version_Required,Downloads
10471,ps_id-34851,Business,3.35,20.0,3.2M,Free,Everyone,Jun 02 2016,1,2.2 and up,"1,000+"
10472,ps_id-12139,NaN,Books And Reference,4.4,384368,Varies with device,Free,Everyone,Sep 08 2019,Varies with device,Varies with device

In [25]:
#By shifting the row right by 1 we get actual value of ratingÂ¶

In [26]:
df["Last_Updated_On"] = pd.to_datetime(df['Last_Updated_On'])
df['year_added']=df['Last_Updated_On'].dt.year
df['month_added']=df['Last_Updated_On'].dt.month

ParserError: Unknown string format: Everyone

In [ ]:
import plotly
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)
col = "Type"
grouped = df[col].value_counts().reset_index()
grouped = grouped.rename(columns = {col : "count", "index" : col})

## plot
trace = go.Pie(labels=grouped[col], values=grouped['count'], pull=[0.05, 0])
layout = {'title': 'Target(0 = No, 1 = Yes)'}
fig = go.Figure(data = [trace], layout = layout)
iplot(fig)